export const eventIdContent = `
# Event ID & Reconciliation

Every transaction the SDK sends to the terminal is tagged with a unique
**event_id**. This ID is your safety net for crash recovery, duplicate
detection, and audit trails.

---

## What is an event_id?

An \`event_id\` is a UUID v4 string generated by the SDK before the request is
sent. It is included in the PAD Controller frame and echoed back in the
terminal's response.

\`\`\`text
SDK generates event_id  ──►  Terminal records event_id
                        ◄──  Terminal echoes event_id in response
\`\`\`

---

## When is it delivered?

\`event_id\` is delivered in the **\`onStarted\`** callback, which fires as soon
as the terminal acknowledges receipt of the request (before processing begins).

> **This is your last chance to persist it before the terminal processes the payment.**

\`\`\`kotlin
override fun onStarted(eventId: String) {
    // Persist IMMEDIATELY — before any UI update
    database.transactions.insert(
        TransactionRecord(eventId = eventId, status = "PENDING")
    )
}
\`\`\`

---

## Crash recovery flow

\`\`\`text
1. App calls doTransaction()
2. onStarted(eventId) fires → App persists eventId
3. App crashes (or network drops, or power loss)
4. App restarts
5. App finds PENDING record with eventId
6. App calls sdk.getStatus(eventId, listener)
7. Terminal returns final status → App updates record
\`\`\`

---

## Duplicate detection

Because the SDK generates a new UUID for each call, retrying after a crash
will generate a **different** \`event_id\`. The terminal treats this as a new
transaction.

If you need idempotency (e.g., retry exactly once), supply your own
\`event_id\` in the request:

\`\`\`kotlin
val request = TransactionRequest(
    transactionType = TransactionType.SALE,
    amount = 50000,
    eventId = "my-system-order-id-12345"   // supply your own
)
\`\`\`

The terminal deduplicates on \`event_id\`: if a transaction with that ID was
already completed, the terminal returns the original result without charging
again.

---

## Reconciliation report

The terminal exposes a reconciliation endpoint (TCP transport only):

\`\`\`http
GET /api/v1/reconcile?from=2024-01-01&to=2024-01-31
Authorization: Bearer <token>
\`\`\`

Response: array of \`TransactionResult\` objects, each with \`event_id\`,
\`status\`, \`amount\`, \`timestamp\`.
`

